import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  {children}

  <footer
    style={{
      marginTop: "6rem",
      padding: "2rem 1.5rem",
      borderTop: "1px solid #e5e7eb",
      fontSize: "0.9rem",
      color: "#555",
    }}
  >
    <div style={{ maxWidth: "1000px", margin: "0 auto" }}>
      <p>
        © {new Date().getFullYear()} Kreyai Technologies LLC
      </p>

      <nav style={{ marginTop: "0.75rem" }}>
        <a href="/pricing" style={{ marginRight: "1rem" }}>Pricing</a>
        <a href="/faq" style={{ marginRight: "1rem" }}>FAQ</a>
        <a href="/privacy" style={{ marginRight: "1rem" }}>Privacy</a>
        <a href="/terms" style={{ marginRight: "1rem" }}>Terms</a>
        <a href="mailto:support@kreyai.com">Contact</a>
      </nav>
    </div>
  </footer>
</body>

    </html>
  );
}
